import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
// login page
  await page.goto('https://demo.easyhr.dev/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('dev+1@easyhrworld.com');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('r0cketInsky!');
  await page.getByRole('button', { name: 'Sign in' }).click();
//   Branches  
  await page.getByRole('button', { name: 'Avatar Kanhai Chhugani' }).click();
  await page.getByText('Settings', { exact: true }).click();
  await page.getByRole('link', { name: 'Data Master' }).click();
  await page.locator('button:nth-child(3)').click();
  await page.locator('[data-test="name"]').click();
  await page.locator('[data-test="name"]').fill('test_1');
  await page.locator('[data-test="description"]').click();
  await page.locator('[data-test="description"]').fill('test_1');
  await page.getByRole('button', { name: 'Search for employee' }).click();
  await page.getByRole('textbox', { name: 'Search Manager' }).fill('Kanhai');
  await page.getByText('Kanhai Chhugani (0001)').click();
  await page.locator('[data-test="address-1"]').click();
  await page.locator('[data-test="address-1"]').fill('test_1');
  await page.locator('[data-test="address-2"]').click();
  await page.locator('[data-test="address-2"]').fill('test_1');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('textbox', { name: 'Search Items' }).click();
  await page.getByRole('textbox', { name: 'Search Items' }).fill('test_1');
  await page.getByTitle('test_1').click();
  await page.getByRole('row', { name: 'test_1 test_1' }).locator('button').click();
  await page.getByRole('menuitem', { name: 'Delete' }).click();
  await page.getByRole('textbox', { name: 'DELETE' }).click();
  await page.getByRole('textbox', { name: 'DELETE' }).fill('D');
  await page.getByRole('textbox', { name: 'DELETE' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'DELETE' }).fill('DELETE');
  await page.getByRole('button', { name: 'Confirm' }).click();
  // Business Segments
  await page.locator('li:nth-child(2) > .relative > .flex').click();
  await page.locator('button:nth-child(3)').click();
  await page.locator('[data-test="name"]').click();
  await page.locator('[data-test="name"]').fill('test_1');
  await page.locator('[data-test="description"]').click();
  await page.locator('[data-test="description"]').fill('test_1');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('textbox', { name: 'Search Items' }).click();
  await page.getByRole('textbox', { name: 'Search Items' }).fill('test_1');
  await page.getByTitle('test_1').click();
  await page.getByRole('row', { name: 'test_1 test_1' }).locator('button').click();
  await page.getByRole('menuitem', { name: 'Delete' }).click();
  await page.getByRole('textbox', { name: 'DELETE' }).click();
  await page.getByRole('textbox', { name: 'DELETE' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'DELETE' }).fill('DELETE');
  await page.getByRole('button', { name: 'Confirm' }).click();
  // Business Verticals
  await page.locator('li:nth-child(3) > .relative > .flex').click();
  await page.locator('button:nth-child(3)').click();
  await page.locator('[data-test="name"]').click();
  await page.locator('[data-test="name"]').fill('');
  await page.locator('[data-test="name"]').press('Tab');
  await page.locator('[data-test="description"]').press('Tab');
  await page.getByRole('button', { name: 'Cancel' }).press('CapsLock');
  await page.locator('[data-test="name"]').click();
  await page.locator('[data-test="name"]').fill('test_1');
  await page.locator('[data-test="description"]').click();
  await page.locator('[data-test="description"]').fill('test_1');
  await page.getByRole('button', { name: 'Search for employee' }).click();
  await page.getByRole('textbox', { name: 'Search Manager' }).click();
  await page.getByRole('textbox', { name: 'Search Manager' }).fill('kanhai');
  await page.getByText('Kanhai Chhugani (0001)').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('textbox', { name: 'Search Items' }).click();
  await page.getByRole('textbox', { name: 'Search Items' }).fill('test_1');
  await page.getByTitle('test_1').click();
  await page.getByRole('row', { name: 'test_1 test_1' }).locator('button').click();
  await page.getByRole('menuitem', { name: 'Delete' }).click();
  await page.getByRole('textbox', { name: 'DELETE' }).click();
  await page.getByRole('textbox', { name: 'DELETE' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'DELETE' }).fill('DELETE');
  await page.getByRole('textbox', { name: 'DELETE' }).press('CapsLock');
  await page.getByRole('button', { name: 'Confirm' }).click();
  //cost centres
  await page.locator('li:nth-child(4) > .relative > .flex').click();
  await page.locator('button:nth-child(3)').click();
  await page.locator('[data-test="name"]').click();
  await page.locator('[data-test="name"]').fill('test_1');
  await page.locator('[data-test="description"]').click();
  await page.locator('[data-test="description"]').fill('test_1');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('textbox', { name: 'Search Items' }).click();
  await page.getByRole('textbox', { name: 'Search Items' }).fill('test_1');
  await page.getByTitle('test_1').click();
  await page.getByRole('row', { name: 'test_1 test_1' }).locator('button').click();
  await page.getByRole('menuitem', { name: 'Delete' }).click();
  await page.getByRole('textbox', { name: 'DELETE' }).click();
  await page.getByRole('textbox', { name: 'DELETE' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'DELETE' }).fill('DELETE');
  await page.getByRole('button', { name: 'Confirm' }).click();
});